name: runnable
on:
  push:
    branches:
      - master

defaults:
  run:
    working-directory: example

jobs:
  runnable:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [9.x, 10.x, 11.x, 12.x, 13.x, 14.x, 15.x, 16.x, 17.x, 18.x]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: |
        npm install
        npm install -g typescript
        npm install -g ts-node

    - name: Run with CommonJS
      run: node commonjs.js

    - name: Run with ES6
      run: ts-node es6.ts
