name: runnable old node
on: [push]

defaults:
  run:
    working-directory: example

jobs:
  runnable:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [6, 7, 8]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: |
        npm install

    - name: Run with CommonJS
      run: node commonjs.js
